FROM apache/airflow:2.10.0

USER root

RUN apt-get update && apt-get install -y docker.io && apt-get clean

USER airflow

RUN pip install --no-cache-dir \
    pandas \
    sqlalchemy \
    psycopg2-binary \
    minio \
    requests \
    pyyaml \
    python-dotenv \
    faker \
    pyreadstat